== Input from Key Presses
:toc:
:!numbered:

Input handling is outside the scope of OpenGL - we can handle input any way we choose. In these examples we were using the https://libsdl.org/[SDL library] for input handling.

In the underlying operating system, each key press and each key release generates an *event*. SDL stores these events for us and to handle input we need to process the event list and use this information to set variables in our *"game state"*.

=== Game State

In this example, we'll just set the C++ `color` variable. Our render loop can then *use* this variable to set the uniform for the color.

[source,c++]
.ourVariables
----
include::main.cpp[tags=ourVariables]
----

=== Setting Game State with input

Each frame we should check for input events, and respond to each.

WARNING: with input handling we should only *SET* parts of our game state. We shouldn't do any OpenGL calls. We also shouldn't do any simulation changes. These should take place in an `updateSimulation` stage.

[source,c++]
.handleInput
----
include::main.cpp[tags=handleInput]
----


include::../../doc/_includes/gettingTheSource.asciidoc[]

include::../../doc/_includes/buildAndRunShort.asciidoc[]
